#ifndef RX_RUNTIME_MATERIAL_PALETTE_H_
#define RX_RUNTIME_MATERIAL_PALETTE_H_

#include <string>

namespace rx {

// Prints the material palette in `dir` as json, one entry per .rxscene file:
// the name an author picks a material by, the path a Prefab.path names it with,
// the file's leading comment as its summary, and the props the preset actually
// sets. This is the answer to "what materials exist", which --dump-schema does
// not have: that documents the components a scene may use, not the content the
// project ships.
//
// Generated by LOADING every file, for the same reason --dump-schema is
// generated from the reflection registry rather than written by hand: an index
// maintained beside the content goes stale the first time someone adds a file
// and forgets. It also means the listing cannot name a preset that does not
// load, which is why a preset that does not is a failure and not a skip.
//
// False (having said which file and why) on a directory that is not there, a
// directory with no presets in it, and a preset that does not load.
bool DumpMaterialPalette(const std::string& dir);

}  // namespace rx

#endif  // RX_RUNTIME_MATERIAL_PALETTE_H_
