# Writes every rx-owned target (engine modules, the viewer, the editor, tools,
# tests) to ${CMAKE_BINARY_DIR}/modules.json: its sources, include directories
# and link libraries as CMake holds them. tools/checkincludes reads it, so the
# build files stay the single source of truth for what may include what.
# Must run after every target exists (the end of the top-level CMakeLists).

function(_rx_collect_targets dir out)
  get_property(targets DIRECTORY ${dir} PROPERTY BUILDSYSTEM_TARGETS)
  set(result ${targets})
  get_property(subdirs DIRECTORY ${dir} PROPERTY SUBDIRECTORIES)
  foreach(subdir ${subdirs})
    cmake_path(IS_PREFIX PROJECT_SOURCE_DIR "${subdir}" NORMALIZE inside)
    cmake_path(IS_PREFIX CMAKE_BINARY_DIR "${subdir}" NORMALIZE generated)
    string(FIND "${subdir}" "${PROJECT_SOURCE_DIR}/third_party" third_party_at)
    if(inside AND NOT generated AND NOT third_party_at EQUAL 0)
      _rx_collect_targets(${subdir} sub)
      list(APPEND result ${sub})
    endif()
  endforeach()
  set(${out} ${result} PARENT_SCOPE)
endfunction()

function(_rx_json_array out)
  set(json "[]")
  set(i 0)
  foreach(item ${ARGN})
    string(JSON json SET "${json}" ${i} "\"${item}\"")
    math(EXPR i "${i} + 1")
  endforeach()
  set(${out} "${json}" PARENT_SCOPE)
endfunction()

function(rx_write_module_graph)
  _rx_collect_targets(${PROJECT_SOURCE_DIR} targets)
  set(json "{}")
  string(JSON json SET "${json}" source_root "\"${PROJECT_SOURCE_DIR}\"")
  string(JSON json SET "${json}" targets "{}")
  foreach(target ${targets})
    get_target_property(type ${target} TYPE)
    if(NOT type MATCHES "^(STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY|INTERFACE_LIBRARY|EXECUTABLE)$")
      continue()
    endif()
    get_target_property(source_dir ${target} SOURCE_DIR)
    set(sources "")
    if(NOT type STREQUAL "INTERFACE_LIBRARY")
      get_target_property(raw_sources ${target} SOURCES)
      foreach(src ${raw_sources})
        if(src MATCHES "^\\$<")
          continue()
        endif()
        cmake_path(ABSOLUTE_PATH src BASE_DIRECTORY ${source_dir} NORMALIZE)
        list(APPEND sources ${src})
      endforeach()
    endif()
    # Generator expressions are passed through as text; the lint strips the
    # BUILD_INTERFACE wrappers and ignores the rest (platform-only links).
    set(props "")
    foreach(prop INCLUDE_DIRECTORIES LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
      if(type STREQUAL "INTERFACE_LIBRARY" AND NOT prop STREQUAL "INTERFACE_LINK_LIBRARIES")
        set(value "")
      else()
        get_target_property(value ${target} ${prop})
        if(NOT value)
          set(value "")
        endif()
      endif()
      string(REPLACE "\"" "\\\"" value "${value}")
      _rx_json_array(${prop} ${value})
    endforeach()
    _rx_json_array(sources_json ${sources})
    set(entry "{}")
    string(JSON entry SET "${entry}" type "\"${type}\"")
    string(JSON entry SET "${entry}" source_dir "\"${source_dir}\"")
    string(JSON entry SET "${entry}" sources "${sources_json}")
    string(JSON entry SET "${entry}" include_dirs "${INCLUDE_DIRECTORIES}")
    string(JSON entry SET "${entry}" link "${LINK_LIBRARIES}")
    string(JSON entry SET "${entry}" interface_link "${INTERFACE_LINK_LIBRARIES}")
    string(JSON json SET "${json}" targets ${target} "${entry}")
  endforeach()
  file(WRITE ${CMAKE_BINARY_DIR}/modules.json.tmp "${json}\n")
  file(COPY_FILE ${CMAKE_BINARY_DIR}/modules.json.tmp ${CMAKE_BINARY_DIR}/modules.json
    ONLY_IF_DIFFERENT)
endfunction()
