// pattern_gen.cc - standalone generator for the ordered-dither placement
// pattern used by the GENERATE stage of GPU procedural placement.
//
// Builds N=256 sample positions in the unit tile, ordered so that any prefix
// of the sequence is an evenly spaced, blue-noise-like point set. Ordering is
// greedy farthest-point selection under a *toroidal* (wrap-around) metric, so
// the tile repeats seamlessly across the world.
//
// Deterministic: fixed-seed PCG32, no std::random_device. Rerunning produces
// byte-identical output.
//
// Build: g++ -std=c++20 -O2 pattern_gen.cc -o pattern_gen
// Usage: ./pattern_gen [output_header_path]   (default: placement_pattern.h)

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <limits>
#include <string>
#include <vector>

namespace {

// ---- PCG32: minimal, deterministic, self-contained ------------------------
struct Pcg32 {
  uint64_t state = 0;
  uint64_t inc = 0;

  Pcg32(uint64_t seed, uint64_t seq) {
    state = 0;
    inc = (seq << 1u) | 1u;
    next();
    state += seed;
    next();
  }

  uint32_t next() {
    uint64_t old = state;
    state = old * 6364136223846793005ULL + inc;
    uint32_t xorshifted = static_cast<uint32_t>(((old >> 18u) ^ old) >> 27u);
    uint32_t rot = static_cast<uint32_t>(old >> 59u);
    return (xorshifted >> rot) | (xorshifted << ((-rot) & 31u));
  }

  // uniform float in [0,1)
  float nextf() {
    // 24 bits of mantissa -> exact in [0,1)
    return (next() >> 8) * (1.0f / 16777216.0f);
  }
};

// Toroidal squared distance on the unit square.
inline float torusDist2(float ax, float ay, float bx, float by) {
  float dx = ax - bx;
  if (dx < 0.0f) dx = -dx;
  if (dx > 0.5f) dx = 1.0f - dx;
  float dy = ay - by;
  if (dy < 0.0f) dy = -dy;
  if (dy > 0.5f) dy = 1.0f - dy;
  return dx * dx + dy * dy;
}

}  // namespace

int main(int argc, char** argv) {
  const std::string outPath = (argc > 1) ? argv[1] : "placement_pattern.h";

  constexpr int N = 256;
  // Candidate pool: stratified jitter, one point per cell of a G x G grid.
  // G = sqrt(4N) = 32 -> 1024 candidates (4x the target count).
  constexpr int G = 32;
  constexpr int kPool = G * G;  // 1024

  // Fixed seeds - changing these changes the (still deterministic) pattern.
  Pcg32 rng(0x9E3779B97F4A7C15ULL, 0xDA3E39CB94B95BDBULL);

  struct Cand {
    float x, y;
    float mind2;      // min toroidal dist^2 to the current selected set
    bool selected;
  };
  std::vector<Cand> pool(kPool);

  const float inv = 1.0f / static_cast<float>(G);
  int idx = 0;
  for (int gy = 0; gy < G; ++gy) {
    for (int gx = 0; gx < G; ++gx) {
      float jx = rng.nextf();
      float jy = rng.nextf();
      float x = (static_cast<float>(gx) + jx) * inv;
      float y = (static_cast<float>(gy) + jy) * inv;
      // guard against exactly 1.0 from float rounding
      if (x >= 1.0f) x = 0.9999990f;
      if (y >= 1.0f) y = 0.9999990f;
      pool[idx++] = Cand{x, y, std::numeric_limits<float>::infinity(), false};
    }
  }

  std::vector<float> outX(N), outY(N);

  // First point: arbitrary, from the PRNG.
  int firstIdx = static_cast<int>(rng.next() % static_cast<uint32_t>(kPool));
  pool[firstIdx].selected = true;
  outX[0] = pool[firstIdx].x;
  outY[0] = pool[firstIdx].y;

  // Seed every candidate's cached min-distance against the first pick.
  for (int c = 0; c < kPool; ++c) {
    if (pool[c].selected) continue;
    float d2 = torusDist2(pool[c].x, pool[c].y, outX[0], outY[0]);
    if (d2 < pool[c].mind2) pool[c].mind2 = d2;
  }

  // Greedy farthest-point: each step picks the candidate whose minimum
  // distance to the already-selected set is largest, then updates the cache
  // against just that newly selected point. O(N * pool).
  for (int k = 1; k < N; ++k) {
    int best = -1;
    float bestd2 = -1.0f;
    for (int c = 0; c < kPool; ++c) {
      if (pool[c].selected) continue;
      if (pool[c].mind2 > bestd2) {
        bestd2 = pool[c].mind2;
        best = c;
      }
    }
    pool[best].selected = true;
    outX[k] = pool[best].x;
    outY[k] = pool[best].y;

    float sx = outX[k], sy = outY[k];
    for (int c = 0; c < kPool; ++c) {
      if (pool[c].selected) continue;
      float d2 = torusDist2(pool[c].x, pool[c].y, sx, sy);
      if (d2 < pool[c].mind2) pool[c].mind2 = d2;
    }
  }

  // ---- Write the generated header ------------------------------------------
  FILE* f = std::fopen(outPath.c_str(), "wb");
  if (!f) {
    std::fprintf(stderr, "pattern_gen: cannot open %s for writing\n",
                 outPath.c_str());
    return 1;
  }

  std::fprintf(f,
      "// Generated by pattern_gen.cc - do not edit by hand.\n"
      "#pragma once\n"
      "#include <cstdint>\n"
      "namespace rx::placement {\n"
      "// Ordered-dither sample pattern: unit-tile positions ordered so that any\n"
      "// prefix is an evenly spaced point set. threshold(i) = (i + 0.5f) / kPatternPoints.\n"
      "inline constexpr uint32_t kPatternPoints = %d;\n"
      "inline constexpr float kPatternXY[kPatternPoints * 2] = {\n",
      N);

  for (int i = 0; i < N; ++i) {
    std::fprintf(f, "  %.6gf, %.6gf,\n", outX[i], outY[i]);
  }

  std::fprintf(f,
      "};\n"
      "}  // namespace rx::placement\n");

  std::fclose(f);
  std::fprintf(stderr, "pattern_gen: wrote %d points to %s\n", N, outPath.c_str());
  return 0;
}
